# Generated by Django 5.1.3 on 2024-11-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eisens', '0003_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
