# Generated by Django 5.1.3 on 2024-12-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eisens', '0005_page_category_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
